FROM jboss/keycloak-examples

# RUN dnf install -y sudo && \
#     adduser user && \
#     echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user && \
#     chmod 0440 /etc/sudoers.d/user

WORKDIR /opt/jboss



USER root
RUN yum -y install sudo
# USER test
RUN curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
RUN sudo yum -y install nodejs

# copy over our example folder's stuff and run npm init.
# then run start! need to open up port 3000 however.

ADD /example/package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app

ADD /example/index.html /opt/app
ADD /example/server.js /opt/app

EXPOSE 3030

#CMD ["NPM", "start"]