FROM jboss/keycloak-examples

# RUN dnf install -y sudo && \
#     adduser user && \
#     echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user && \
#     chmod 0440 /etc/sudoers.d/user

WORKDIR /opt/jboss



USER root
RUN yum -y install sudo
# USER test
RUN curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
RUN sudo yum -y install nodejs